stages:
  - deploy

deploy:
  stage: deploy
  image: ubuntu:latest
  variables:
    HOST: ssh.rosti.cz
    USER: app
    PORT: 13276
    PHP_VERSION: 8.3.12
  script:
    - apt-get update && apt-get install -y rsync openssh-client
    - echo "$ROSTI_DEPLOY_SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - echo "ssh.rosti.cz ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvNnayRY/BP5OGT/7stEtjxq9zQ7EpK5juBJBHYKTUELpUXWYlkyxKusU0rhEMVeQRJS3794JIBPp1P0QGheQU/KfH6kYFahOcWHBy149Pe0H0dqoHfD4n460h/qZgqkRW6H41Se0IXZC1OFqgXEgqY+ZZV4m+7LzjZ+pBo/u0dkpqec1A/Ju8pyPMB9NnBdJP0A7vkqBjugjSqxSCtfrzNqGcEvuoYV95uorIIpdYMd/4/c23tSezs1a7/VZIZkk8YZ63rjT1zM7hBfeW/KBRY2e6gguW5EKuLufLxinb/6OmZnFp1MO52z5HOdlDYqdbMiqMpunDMUKw3GWaRy77" > ./known_hosts
    - echo "$ENV" > .env
    - ssh -o UserKnownHostsFile=./known_hosts -p $PORT $USER@$HOST /usr/local/bin/rosti php $PHP_VERSION
    - rsync -ae "ssh -o UserKnownHostsFile=./known_hosts -p $PORT" --delete-after --exclude=.git ./ $USER@$HOST:/srv/app/
    - ssh -o UserKnownHostsFile=./known_hosts -p $PORT $USER@$HOST supervisorctl restart app
