stages:
  - deploy

variables:
  HOST: "ssh.rosti.cz"
  USER: "app"
  PORT: "13276"
  PHP_VERSION: "8.3.12"

deploy:
  stage: deploy
  image: ubuntu:latest
  script:
    - echo "$ROSTI_DEPLOY_SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
    - |
      cat << EOF > .env
      $ENV
      EOF
    - |
      ssh -o UserKnownHostsFile=~/.ssh/known_hosts -p $PORT $USER@$HOST /usr/local/bin/rosti php $PHP_VERSION
    - |
      rsync -ae "ssh -o UserKnownHostsFile=~/.ssh/known_hosts -p $PORT" --delete-after --exclude=.git ./ $USER@$HOST:/srv/app/
    - |
      ssh -o UserKnownHostsFile=~/.ssh/known_hosts -p $PORT $USER@$HOST supervisorctl restart app
  only:
    - main
