stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - docker build -t windows.loc
test-job:
  stage: test
  script:
    - docker run --rm windows.loc
deploy-job:
  stage: deploy
  script:
    - docker compose up -d

